Feature/primera entrega
armandopasilis/Programacion_web_uces pull request #1
Opened 2024-08-23 14:35 UTC by armandopasilis

Desarrolamos el HTML de la pagina Baller Brand San Martin que es un e-comerce de ropa deportiva.

2024-08-23 15:47 UTC, MVelasquez98 requested changes
Falta el archivo readme.md. Laconsigna solicita:
"Antes de iniciar con el desarrollo del proyecto, es fundamental proporcionar una descripción detallada del mismo en el archivo [README.md](https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) de tu repositorio en GitHub. Este archivo actúa como la primera impresión del proyecto para cualquier persona que visite el repositorio, por lo que debe ser claro, conciso y completo"

2024-08-23 15:47 UTC, MVelasquez98 commented on docs/index.html
> +    <title>Document</title>
Es title corresponde al titulo que se ve en el encabezado de la pestaña del navegador. No corresponde "document", tiene que ser un nombre descriptivo del sitio

2024-08-23 15:47 UTC, MVelasquez98 commented on docs/index.html
> +            <h2>Nuestros Productos</h2>
La actividad solicita:
"Incluye elementos básicos como título, párrafos, imágenes, enlaces, listas, formularios y tablas relacionados con tu tema."
Falta utilizar tablas, que bien podría usarse aca una tabla de productos/precios por ejemplo

2024-08-23 15:49 UTC, MVelasquez98 requested changes
El archivo index.html debe estar en el root de la pagina no dentro de una carpeta "docs"
No entiendo a que corresponde la carpeta  "Clase 1" con un index.html vacio, si no es necesario limpiar del repositorio

2024-08-23 15:50 UTC, MVelasquez98 commented on .gitattributes
> +Clase[[:space:]]1/imagenes/rubyinstaller-devkit-3.3.4-1-x64.exe filter=lfs diff=lfs merge=lfs -text
¿A que corresponde esto?

2024-08-23 16:03 UTC, MVelasquez98 requested changes
PUNTAJE POR CONSIGNA:

**Estructura HTML (3 puntos):**
Uso correcto de HTML5 para estructurar la página. ✔️
Completa inclusión de elementos básicos como título, párrafos, imágenes, enlaces, listas y tablas relacionados con el tema elegido. ❌
Introduce etiquetas semánticas pertinentes para mejorar la accesibilidad y el SEO. ✔️

**GitHub (5 puntos):**
Correcta creación de ramas "master" y "develop" en el repositorio. ✔️
Creación de una rama "feature/primera-entrega" y habilitación de GitHub Pages para esa rama. ✔️
Realización de commits necesarios sobre la rama de desarrollo. ✔️
Correcta creación de la pull request contra la rama "develop". ❌ Esta hecha contra la rama "master". Corregir
Entrega de la URL de la pull request y la URL generada por GitHub Pages. ✔️

**Documentación (2 puntos):**
Inclusión de comentarios claros y concisos en el código HTML. ✔️
Realizar una descripción y overview del proyecto elegido en el readme.md del repositorio ❌

**Nota: 7 (Siete)**

2024-08-23 16:06 UTC, armandopasilis commented on docs/index.html
> +    <title>Document</title>
Gracias Profe ahi lo arrelge , el Readme lo genere , no se por que no se ve , lo reviso

2024-08-23 16:26 UTC, armandopasilis commented on docs/index.html
> +            <h2>Nuestros Productos</h2>
realizado

2024-08-23 16:27 UTC, armandopasilis commented on .gitattributes
> +Clase[[:space:]]1/imagenes/rubyinstaller-devkit-3.3.4-1-x64.exe filter=lfs diff=lfs merge=lfs -text
ahi lo borre , se descargo una archivo en imagenes

2024-08-23 18:55 UTC, armandopasilis commented
se cambio rama a develop

2024-09-03 22:33 UTC, armandopasilis commented
Hola Profe , como esta ? para Realizar la segunda entrega deberia de realizar reverse and merge paero antes tendira que darme el visto bueno no ? Gracias

2024-09-04 01:31 UTC, MVelasquez98 commented
@armandopasilis  Falta esta corrección:
"No entiendo a que corresponde la carpeta "Clase 1" con un index.html vacio, si no es necesario eliminar del repositorio"

2024-09-04 17:12 UTC, closed without merging