Release/primer parcial
armandopasilis/Programacion_web_uces pull request #12
Opened 2024-10-03 18:54 UTC by armandopasilis

2024-10-03 19:21 UTC, armandopasilis commented
@MVelasquez98 Profesor si por favor me puede ayudar a  a realizar la entrega de manera correcta , estoy viendo tutoriales y videos pero no aplican la solucion . No se cual es el problema

2024-10-03 19:36 UTC, MVelasquez98 commented
Aunque te de approve no te va dejar hacer merge, por los [conflictos](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) que hay:
![image](https://github.com/user-attachments/assets/fec0397b-c856-4542-945c-2356de041d86)
Podes hacer lo siguiente en tu local:

- Te moves a origin/develop
- Haces git pull
- Volves a la rama feature/segunda-entrega
- Haces desde vscode ... -> Rama -> Fusionar la rama mediante "rebase"

![image](https://github.com/user-attachments/assets/ac60e795-fece-42ae-9c91-20672e16630d)

- Escoges origin/develop del listado.
- [Resolves los conflictos](https://www.jorgeacortes.com/2019/01/resolver-conflictos-en-git-con-visual-studio-code/)que esten en los archivos marcados con advertencia ⚠️
- Asegurate de no pisar tus cambios
- Hace git add .
- Le das "Continuar" (el boton azul)
- Haces git push -f

Algunos videos que te pueden servir:
[Como Solucionar un Merge Conflict (Conflicto de Merge) En VSCode](https://youtu.be/uDDNwwxoaZY?si=eGG_ZhIXRfYpEmnn)
[Cómo resolver conflictos de versiones con VS Code](https://youtu.be/g7bbxEt09PI?si=bi26br5lpoyPY3-w)

2024-10-03 19:57 UTC, armandopasilis commented
Gracias por la ayuda profe , la estoy pasando mal con esto . Pero creo que con esto se aprende también a la fuerza .
Muy amable al tener esta disponibilidad .
Luego de realizar estos paso que me indica cual seria los siguientes ?
Deberia de trabajar con la rama del parcial ?
________________________________
De: Matias Velasquez ***@***.***>
Enviado: jueves, 3 de octubre de 2024 16:36
Para: armandopasilis/Programacion_web_uces ***@***.***>
Cc: armandopasilis ***@***.***>; Author ***@***.***>
Asunto: Re: [armandopasilis/Programacion_web_uces] Release/primer parcial (PR #12)


Aunque te de approve no te va dejar hacer merge, por los conflictos<https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github> que hay:
image.png (view on web)<https://github.com/user-attachments/assets/fec0397b-c856-4542-945c-2356de041d86>
Podes hacer lo siguiente en tu local:

  *   Te moves a origin/develop
  *   Haces git pull
  *   Volves a la rama feature/segunda-entrega
  *   Haces desde vscode ... -> Rama -> Fusionar la rama mediante "rebase"

image.png (view on web)<https://github.com/user-attachments/assets/ac60e795-fece-42ae-9c91-20672e16630d>

  *   Escoges origin/develop del listado.
  *   Resolves los conflictos<https://www.jorgeacortes.com/2019/01/resolver-conflictos-en-git-con-visual-studio-code/>que esten en los archivos marcados con advertencia ⚠️
  *   Asegurate de no pisar tus cambios
  *   Hace git add .
  *   Le das "Continuar" (el boton azul)
  *   Haces git push -f

Algunos videos que te pueden servir:
Como Solucionar un Merge Conflict (Conflicto de Merge) En VSCode<https://youtu.be/uDDNwwxoaZY?si=eGG_ZhIXRfYpEmnn>
Cómo resolver conflictos de versiones con VS Code<https://youtu.be/g7bbxEt09PI?si=bi26br5lpoyPY3-w>

—
Reply to this email directly, view it on GitHub<https://github.com/armandopasilis/Programacion_web_uces/pull/12#issuecomment-2392184834>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIJK45DEHATYCQLR4K3VAOLZZWMDLAVCNFSM6AAAAABPKMSULSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJSGE4DIOBTGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-10-03 20:09 UTC, armandopasilis commented
Ya no figura mas el error de Index pero continua sin figurar en verde el boton de rebase and merge ... 
![image](https://github.com/user-attachments/assets/0e5ed18b-b1c5-467e-a562-1278dfac5dcb)

2024-10-03 22:40 UTC, armandopasilis commented
Por lo que lei esto pasa cuando hay varios cambios y el merge no puede garantizar que se convinen los archivos con seguridad .

2024-10-04 02:48 UTC, MVelasquez98 commented
Esta bien que no te deje hacer rebase and merge esta vez, porque esta yendo contra la rama master. Ahí usamos solo merge pull request. Pero eso es más adelante, mientras dejas abierta esta pr para el parcial. 
rebase and mege - > develop, feature
merge pull request -> master, backport, release

2024-10-04 18:45 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Incorporación de Componentes Avanzados de HTML (1 punto):**

- ✅ Agregar al menos un componente avanzado de HTML a la página, como un iframe de un video de YouTube o un mapa de Google Maps. (1 punto).

**Implementación de Bootstrap para Diseño Responsivo (5 puntos):**

- ✅ Instalar la biblioteca Bootstrap en el proyecto. (1 punto)
- ⚠️ Utilizar el sistema de columnas de Bootstrap para hacer que el sitio sea más responsivo en dispositivos móviles. (3 puntos). Podría aprovecharse mejor el [sistema de columnas en Bootstrap](https://getbootstrap.esdocu.com/docs/5.1/layout/columns/) o [grilla](https://getbootstrap.com/docs/4.0/layout/grid/) para mejorar el [Diseño UI](https://perio.unlp.edu.ar/catedras/comyddhhlic/wp-content/uploads/sites/125/2023/02/Diseno-UX-UI.pdf), más que nada en dispositivos moviles. 
- ✅  Incluir al menos un componente avanzado de Bootstrap, como un carrusel, una barra de navegación o un modal. (1 punto). No esta funcionando correctamente el navbar en dispositivos moviles.

**Gestión del Proyecto con GitHub (4 puntos):**

- ✅ Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto)
- ✅ Creación de una rama "release/primer-parcial" a partir de la rama "develop" utilizando Git. (1 punto)
- ❌ Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/segunda-entrega" con "develop" en GitHub. (1 punto). Tene cuidado en las proxima entregas de donde estas posicionada a la hora de hacer push de un commit, respeta las pull request para subir los cambios. **Espera mi LGTM** antes de hacer merge. Para evitar conflictos de merge siempre asegurarte de tener los últimos cambios de develop antes de crear la rama de trabajo. El flujo de trabajo quedo un poco desordenado ahora, pero trata de seguir el paso a paso de las proximas entregas. Es una muy mala practica cerrar pr sin explicación o hacer merge sin approve, en el mundo laboral, puede ser un problema grande subir un cambio a un ambiente que no corresponde o corromper el fujo de trabajo de git.
-  ⚠️ Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama "release/primer-parcial" como parte de la entrega. (1 punto) No me proporcionaste la Url de GithubPages en la entrega, tuve que rastrearla manualmente en el repositorio.

**Nota:** 6 (Seis)

2024-10-04 19:08 UTC, MVelasquez98 commented
A modo de observación fijate como quedaron las diferentes ramas de trabajo en tu repositorio, para que veas la importancia de respetar el flujo GitFlow en Git.

✅ **feature/primera-entrega**
![image](https://github.com/user-attachments/assets/5b536805-27df-4cb2-beaa-f729e9c0facc)

❌ **feature/-segunda-entrega**
![image](https://github.com/user-attachments/assets/a87238a4-4607-45f6-861e-7d0ea7e2a0ff)
- Desparecieron las imagenes que deberían estar de la primera entrega
- ¿Donde esta el CSS que se tenia que hacer justamente en esta entrega? 😳

❌ develop
![image](https://github.com/user-attachments/assets/347dc2d8-622f-4d8f-8b1b-af046da06214)
- ¿Porque no estan las imagenes que se supone se tuvieron que hacer merge en la pull request de la primera entrega? 😳
- ¿Donde esta el CSS que se tenia que mergear en la segunda entrega? 😳
- Si se supone el parcial parte de las entregas 1 y 2 con el HTML y CSS que tendrian que estar en develop ¿De donde salio todo eso para el parcial?¿Quien lo valido?😐

❌  master
![image](https://github.com/user-attachments/assets/d43b4e40-5afa-4d82-b846-bebeb506ab82)
- Master tendría que estar vacia. Esto en la vida real sería Producción ‼️ ‼️ ‼️ ‼️ ‼️ ‼️ ‼️ ‼️ ‼️ ‼️ ‼️ ‼️ ‼️ 
- ¿Cómo llegaron cambios ahí si la release del parcial no esta cerrada? ¿Esos cambios pasaron si pull request?¿Sin approve? 😳💀

Vas a tener la oportunidad de corregir estos cambios en la tercera entrega, pero seguí el procedimiento de entrega de la consigna paso a paso. Solicita aprobación, pregunta. Esto en un trabajo real es gravisimo, aca es menos puntos en un parcial.

2024-10-07 23:06 UTC, armandopasilis commented
Hola profe, como esta ? gracias por la devolucion , la paciencia y la predispocicion . Que me recomienda para solucionar el git flow del trabajo ? o continuo de eta manera ? . Creo que muchas de las modificaciones que hicieron en las distintas ramas dfueron por ejecutar en la consola distintos reset .Voy a ver si puedo ir viendo cursos para ponerme mas en linea con la cursada . Para el siguiente TP le debo pedir el LGTM en esta pull ? @MVelasquez98

2024-10-14 19:11 UTC, armandopasilis commented
Hola Profe solicito la aprovacion para continuar con los TP . Solicito el LGTM @MVelasquez98

2024-10-15 11:37 UTC, MVelasquez98 approved these changes
LGTM
Concentrate en seguir bien los pasos a partir de ahora, crea bien el backport contra develop, para que los cambios del parcial lleguen a la rama de desarrollo. A partir de ahí empeza con la actividad 3. Con eso deberías restablecer el flujo de git al menos en develop. Despúes podes revisar individualmente cada rama y asegurarte de que tenga  los archivos y cambios que corresponden a cada entrega.

2024-10-15 11:37 UTC, MVelasquez98 commented on index.html
> +                <form action="ruta_del_servidor_de_correo" method="post" class="mx-auto" style="max-width: 600px;">
El formulario no se comporta de forma responsiva en dispositivos moviles, ni en pantallas grandes:
![image](https://github.com/user-attachments/assets/71237cb7-b9b6-48df-8418-fead7e5e71a6)
Podes aprovecharte de los [formularios](https://getbootstrap.com/docs/4.0/components/forms/) en Bootstrap para mejorar el diseño responsivo.

2024-10-15 11:37 UTC, MVelasquez98 commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
Si vas a poner el script al principio del archivo tenes que agregar el atributo [defer](https://www.w3schools.com/tags/att_script_defer.asp) al final, sino solamente pones el script al final de todo dentro del body. Esto para evitar errores asyncronicos a futuro.

2024-10-16 19:57 UTC, merged