Feature/tercera entrega
armandopasilis/Programacion_web_uces pull request #14
Opened 2024-10-22 12:42 UTC by armandopasilis

3 ENTREGA Requerimientos para esta entrega:
1. Algoritmos:
● Se utiliza algoritmo condicional y con ciclo (IF, bucles for) de manera
óptima , reflejando lo aprendido en la unidad.
2. Funciones:
● Los nombres de las funciones son claros y dan a entender que acción
realizan.
● Crear funciones y/o métodos para realizar operaciones (suma, resta,
concatenación, división, porcentaje, etc).
● Se emplea la estructura correcta para el armado de las mismas.
● Crea funciones dinámicas de manera correcta.
● Generan un resultado correcto cuando se ejecutan.
3. Funcionalidad:
● Se simula un flujo de trabajo en términos de entrada,proceso y salida.
● La funcionalidad es apropiada al contexto del simulador.
● Pensar el alcance de tu proyecto: ¿usarás un cotizador de seguros?
¿un simulador de créditos? ¿un simulador personalizado?
4. Interactividad:
● Se capturan una o más entradas ingresadas por el usuario con
prompt().
● Se efectúan una o más salidas con alert() o console.log().
● Las salidas son coherentes en relación a los datos ingresados.
5. Escalabilidad:
● Se declaran funciones con parámetros para definir instrucciones con
una tarea específica.
● Se emplean arrays para agrupar valores relacionados.
● Se definen objetos con propiedades y métodos relevantes al contexto.
6. Integridad:
● Se define el código JavaScript en un archivo .js, referenciándolo
correctamente desde el HTML.
● Se emplea correctamente prompt() y alert() sin generar interrupciones
del procesamiento.
7. Legibilidad:
● Los nombres de variables. funciones y objetos son significativos para el
contexto. Se utiliza el naming correspondiente con camelCase o
PascalCase (según corresponda).
● Las instrucciones se escriben de forma legible y se emplean
comentarios oportunos.
● El código está correctamente estructurado, alineado e indentado. Se
puede utilizar alguna extensión para ello.

2024-10-24 18:23 UTC, MVelasquez98 requested changes
No me proporcionaste la URL de github pages, no hiciste deploy de estos cambios en el servidor, no tengo manera de probar tu código a nivel funcional.
![image](https://github.com/user-attachments/assets/19f46d74-95c7-40ea-a35c-69e3fbc12a1e)

2024-10-24 18:39 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Algoritmos (1 punto)**
✅ 1 punto: Uso correcto y eficiente de algoritmos condicionales y ciclos.

- **Funciones (1 punto)**
✅ 1 punto: Funciones con nombres claros, estructura correcta y resultados correctos.

- **Funcionalidad (1 punto)**
✅ 1 punto: Flujo de trabajo completo y funcionalidad apropiada al contexto. Código JavaScript correctamente referenciado y uso adecuado de prompt() y alert().

- **Interactividad (1 punto)**
✅ 1 punto: Interactividad adecuada y salidas coherentes.

- **Escalabilidad (1 punto)**
⚠️ 0.5 puntos: Falta de funciones con parámetros y el uso de [Clases](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes) con métodos. Ej: `function myFunction(param, param2)`

- **Legibilidad (1 punto)**
✅ 1 punto: Nombres significativos, código legible y bien estructurado.

- **GitHub (4 puntos):**

✅ 1 punto: Creación de una rama "backport/primer-parcial" a partir de la rama "master" utilizando Git.
⚠️ 0.5 puntos:: Creación de una rama "feature/tercera-entrega" a partir de la rama "develop" utilizando Git. No proporcionaste el enlace de Github Pages
✅ 1 punto: Correcta realización de la solicitud de revisión para fusionar la rama "backport/primer-parcial" con "develop" en GitHub, resolviendo los conflictos de merge (si fuese necesario).
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "release/primer-parcial" con "master" en GitHub, resolviendo los conflictos de merge (si fuese necesario).
Nota: 9(Nueve)

2024-10-24 18:39 UTC, MVelasquez98 commented on script.js
> +    { id: 1, nombre: "Conjunto deportivo Chicago", precio: 2500 },
¿Por qué no definir una Clase Producto?

2024-11-03 21:05 UTC, armandopasilis commented
https://armandopasilis.github.io/Programacion_web_uces/


![image](https://github.com/user-attachments/assets/2992d6b2-d735-462b-bd90-15a597b616a7)

2024-11-03 21:06 UTC, armandopasilis commented on script.js
> +    { id: 1, nombre: "Conjunto deportivo Chicago", precio: 2500 },
No se me ocurrio , ahora lo agrego

2024-11-03 21:06 UTC, armandopasilis commented
Hola , solicito el LGTM para avanzar con la entrega .Saludos

2024-11-03 22:20 UTC, MVelasquez98 requested changes
Errores en consola:
- Not Found la imagen
![image](https://github.com/user-attachments/assets/9d6fb3df-90bb-4f6c-b479-09192a0a91c6)
![image](https://github.com/user-attachments/assets/20f76a98-910d-4511-a406-d74dba0b3230)
Revisar la consola del navegador

2024-11-03 22:20 UTC, MVelasquez98 commented on script.js
> +// Clase Producto
Para mantener un orden en la estructura del proyecto, las Clases deben estar en otro archivo aparte con su respectivo nombre, tal como vimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009)

2024-11-03 22:22 UTC, MVelasquez98 requested changes
Errores en consola:
Error en importación en bootstrap
![image](https://github.com/user-attachments/assets/c731c9ea-1f78-48a7-8f7d-d2c4e6bcb645)
![image](https://github.com/user-attachments/assets/a72a9fa4-c31f-486f-b048-715a47ed002f)
Revisar en consola del navegador

2024-11-03 22:24 UTC, MVelasquez98 requested changes
El Link que me proporcionaste de GitHub Pages no tiene los últimos cambios que agregaste de JS en esta entrega:
https://armandopasilis.github.io/Programacion_web_uces/
De hecho, no hiciste deploy de esta rama:
![image](https://github.com/user-attachments/assets/1644af1c-49ef-4075-a47c-64543fad64d3)
El último [deploy](https://github.com/armandopasilis/Programacion_web_uces/deployments/github-pages) que hiciste fue hace 3 semanas con el parcial:
![image](https://github.com/user-attachments/assets/99ab3803-4864-4bf7-936a-2700c6e89ef6)

2024-11-04 21:56 UTC, armandopasilis commented
> Errores en consola:
> 
> * Not Found la imagen
>   ![image](https://private-user-images.githubusercontent.com/43156596/382609057-9d6fb3df-90bb-4f6c-b479-09192a0a91c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTc0NzcsIm5iZiI6MTczMDc1NzE3NywicGF0aCI6Ii80MzE1NjU5Ni8zODI2MDkwNTctOWQ2ZmIzZGYtOTBiYi00ZjZjLWI0NzktMDkxOTJhMGE5MWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDIxNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNDAxNTIwMDI2OWVlMjEzNzkxNTJiY2ZjOWZmOTQ4ZjdlNTBkMWRiNGI2ZmMwMzMwZDAwMzMzMzBiYzdlYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kCwInGrD1UHg2N_sP-PM5Oo5g3AyjdOzbVtb7Uu-6YA)
>   ![image](https://private-user-images.githubusercontent.com/43156596/382609074-20f76a98-910d-4511-a406-d74dba0b3230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTc0NzcsIm5iZiI6MTczMDc1NzE3NywicGF0aCI6Ii80MzE1NjU5Ni8zODI2MDkwNzQtMjBmNzZhOTgtOTEwZC00NTExLWE0MDYtZDc0ZGJhMGIzMjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDIxNTI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MmIwOTlmYzk4NGQzMjg4ODg1OWJkMTg1NjlmYWMxODM5NmYzZTJmYzk0M2Q0N2YxN2NkZGI0ZmQ2NzljMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1NFdiYLWxMcI3UshWRl-vY_AEMuEUrzGDHttGDezD4s)
>   Revisar la consola del navegador

si es una imagen que borre

2024-11-04 22:39 UTC, armandopasilis commented on script.js
> +// Clase Producto
Realizado

2024-11-04 22:39 UTC, armandopasilis commented
> Errores en consola: Error en importación en bootstrap ![image](https://private-user-images.githubusercontent.com/43156596/382609180-c731c9ea-1f78-48a7-8f7d-d2c4e6bcb645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTgzMTksIm5iZiI6MTczMDc1ODAxOSwicGF0aCI6Ii80MzE1NjU5Ni8zODI2MDkxODAtYzczMWM5ZWEtMWY3OC00OGE3LThmN2QtZDJjNGU2YmNiNjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDIyMDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMjZhZjdlMzNiYmZmZWJmZDA3YjcxYzQwZDcxMDhlZWJlMjA5YWRjZjU5MzdhMjAzNjg5ODUwNWQ0ZDk4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zpKCokW8qeKZDpeaHdvR_glHUcHrR8a599daYwGCUxg) ![image](https://private-user-images.githubusercontent.com/43156596/382609197-a72a9fa4-c31f-486f-b048-715a47ed002f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTgzMTksIm5iZiI6MTczMDc1ODAxOSwicGF0aCI6Ii80MzE1NjU5Ni8zODI2MDkxOTctYTcyYTlmYTQtYzMxZi00ODZmLWIwNDgtNzE1YTQ3ZWQwMDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDIyMDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3Y2RjZjg0NDFjMGE4MmI0MWIwMmY2ZGM0Y2M3ZDNmODc0Nzg5OWI5MDM4OGM0MGE3N2I0YzNiYTgzN2UwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b9il4YXEep-cU63m225p1PE_oGqKrYMO-eqY88rJuTc) Revisar en consola del navegador

Realizado

2024-11-05 00:31 UTC, MVelasquez98 requested changes
Te sigue faltando hacer deploy de esta branch en GithubPages, revisa la [documentación](https://docs.github.com/es/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch) para configurar una branch especifica.
Fijate el [listado de deploys](https://github.com/armandopasilis/Programacion_web_uces/deployments/github-pages), hace 3 semanas fue el último:
<img width="578" alt="image" src="https://github.com/user-attachments/assets/8e73aa2f-ec04-4a62-820e-684980326b89">
Si te sigue apareciendo esto en la pull request, enttonces es que el deploy no esta aún:
<img width="343" alt="image" src="https://github.com/user-attachments/assets/8f902916-2bf4-45c4-bc5a-1b3cc839bc73">

2024-11-05 07:23 UTC, armandopasilis commented
> Te sigue faltando hacer deploy de esta branch en GithubPages, revisa la [documentación](https://docs.github.com/es/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch) para configurar una branch especifica. Fijate el [listado de deploys](https://github.com/armandopasilis/Programacion_web_uces/deployments/github-pages), hace 3 semanas fue el último: <img alt="image" width="578" src="https://private-user-images.githubusercontent.com/43156596/382963176-8e73aa2f-ec04-4a62-820e-684980326b89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTE0NjEsIm5iZiI6MTczMDc5MTE2MSwicGF0aCI6Ii80MzE1NjU5Ni8zODI5NjMxNzYtOGU3M2FhMmYtZWMwNC00YTYyLTgyMGUtNjg0OTgwMzI2Yjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA3MTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZGI2N2ZhOTA4ZmE5YTkxZjM4ZDg5ZWVkODQxNDRhZDJmZjc1N2RkODcyYTFmZGE1ZDQxMjM2ODhmMDQ4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L0CYHl20XvfXBBD0tAAFmp7sQJ8-cQ53wchtGAOnJis"> Si te sigue apareciendo esto en la pull request, enttonces es que el deploy no esta aún: <img alt="image" width="343" src="https://private-user-images.githubusercontent.com/43156596/382963467-8f902916-2bf4-45c4-bc5a-1b3cc839bc73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTE0NjEsIm5iZiI6MTczMDc5MTE2MSwicGF0aCI6Ii80MzE1NjU5Ni8zODI5NjM0NjctOGY5MDI5MTYtMmJmNC00NWM0LWJjNWEtMWIzY2M4MzliYzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA3MTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYWE1NTc5OWQ2M2E0NGFkNmQzZTdiMmNmMTZlYTBlYTM1YWUzZTU3OWM0NDI0NmI1YjEyNDhjYjMzYzdhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OBqZOPX5MRx_cxCQRrwqOd3lUcPCdO13DZQ_oDz5Sb4">

![image](https://github.com/user-attachments/assets/faea4d45-9daf-433c-93b5-31a7ead21a4a)

2024-11-05 07:23 UTC, armandopasilis commented
![image](https://github.com/user-attachments/assets/c13ace99-f750-4d65-9c8f-50bae89b3590)
creo que ahora figura bien

2024-11-05 16:52 UTC, MVelasquez98 requested changes
Fijate el listado de deploys, el único activo es el de la rama "master"
![image](https://github.com/user-attachments/assets/c2b7a873-4340-4ab4-a95d-cd14d74dcc32)
Proba entrando al link https://armandopasilis.github.io/Programacion_web_uces/
¿Ves tus últimos cambios?¿Podes probar la funcionalidad de JS?
Aparentemente hiciste un deploy de la rama pero despúes quedo inactivo como indica la pr:
![image](https://github.com/user-attachments/assets/a7174118-1eef-4c74-81ee-91d745413e83)
Asegurate de seguir correctamente la [documentación de Github ](https://docs.github.com/es/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch)sobre esto.
Te dejo un [video](https://youtu.be/ddqXpFytmiQ?si=AwfG28jLsycTNU0A) que puede ayudarte.
Asegurarte de seleccionar la rama correcta "feature/tercera-entrega", y para probar que funciona tendrías que entrar a esta url  https://armandopasilis.github.io/Programacion_web_uces/ y poder ver y probar tus últimos cambios.

2024-11-06 21:55 UTC, armandopasilis commented
> Fijate el listado de deploys, el único activo es el de la rama "master" ![image](https://private-user-images.githubusercontent.com/43156596/383237646-c2b7a873-4340-4ab4-a95d-cd14d74dcc32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjMxNDAsIm5iZiI6MTczMDkyMjg0MCwicGF0aCI6Ii80MzE1NjU5Ni8zODMyMzc2NDYtYzJiN2E4NzMtNDM0MC00YWI0LWE5NWQtY2QxNGQ3NGRjYzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE5NTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYTg5NjU0OGRkZTVhMmExNWZjMzhkZjEwNDE3NGEyNzllZDUwMWQ0YmVhOWNiODc1MzU0YzRmMjZiODhlNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zLlmR9up7T_5Whu7DKjl4Ar0IL2jd07SGw-HPSzl8lk) Proba entrando al link https://armandopasilis.github.io/Programacion_web_uces/ ¿Ves tus últimos cambios?¿Podes probar la funcionalidad de JS? Aparentemente hiciste un deploy de la rama pero despúes quedo inactivo como indica la pr: ![image](https://private-user-images.githubusercontent.com/43156596/383238151-a7174118-1eef-4c74-81ee-91d745413e83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjMxNDAsIm5iZiI6MTczMDkyMjg0MCwicGF0aCI6Ii80MzE1NjU5Ni8zODMyMzgxNTEtYTcxNzQxMTgtMWVlZi00Yzc0LTgxZWUtOTFkNzQ1NDEzZTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE5NTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMjQxMzNkNTZhZWVkM2FmNmVhZWRlNzYwZTkxZGNmYjBlZTU5MjU5MGZkNzNhODQ2YjgxMWMzMjlkMDJjNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HlfSB958L-KY-MX2NX7Ioh2rRYveUIFYpiPygd9iIq8) Asegurate de seguir correctamente la [documentación de Github ](https://docs.github.com/es/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch)sobre esto. Te dejo un [video](https://youtu.be/ddqXpFytmiQ?si=AwfG28jLsycTNU0A) que puede ayudarte. Asegurarte de seleccionar la rama correcta "feature/tercera-entrega", y para probar que funciona tendrías que entrar a esta url https://armandopasilis.github.io/Programacion_web_uces/ y poder ver y probar tus últimos cambios.

Listo , ahora si . Gracias

2024-11-06 22:13 UTC, MVelasquez98 approved these changes
LGTM

2024-11-10 19:15 UTC, merged