Merge branch 'feature/tercera-entrega' of https://github.com/armandop…
armandopasilis/Programacion_web_uces pull request #15
Opened 2024-11-17 10:34 UTC by armandopasilis

…asilis/Programacion_web_uces into feature/tercera-entrega

2024-11-21 14:50 UTC, armandopasilis commented
Cambios que hice en el HTML
Primero, agregué un par de campos nuevos para que puedas cargar el nombre del producto y el precio. Así, cada vez que querés agregar algo al carrito, lo cargás con esos datos. También dejé el botón para agregar, pero ahora suma productos en vez de tareas.

Después, la lista (<ul>) la usé para mostrar los productos que vas agregando, con su nombre, precio, y un botón al lado para eliminarlos si querés sacar algo del carrito.

Cambios en el JavaScript

Cambié todo lo de "tareas" por "productos". Ahora, cada producto tiene un nombre y un precio, y los voy mostrando en la lista del carrito.
Agregué una función para calcular el total del carrito. Cada vez que sumás o eliminás algo, el total se recalcula automáticamente.
También metí un botón de eliminar en cada producto que cargás. Si lo apretás, borra ese producto del carrito y actualiza el total.

2024-11-22 18:20 UTC, MVelasquez98 commented
No corresponde entregar más cambios fuera del plazo establecido. Solo incorporar cambios posterior a la correción.

2024-11-25 04:59 UTC, MVelasquez98 commented
No se entiende el flujo de entrada - procesamiento - salida. Cuando hago click en comprar a un producto me aparece este modal vacio:
<img width="1356" alt="image" src="https://github.com/user-attachments/assets/82f9526b-5de0-43ea-95bd-5cfd857926a3">
Y despúes por otro lado tengo este formulario donde puedo agregar productos al carrito, pero puede ser cualquier cosa sin ninguna validacion, no tiene sentido:
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/7e899dd7-0149-4aad-8576-3bd813d267f4">
No hay una salida, de finalizar la compra en este caso.

2024-11-25 05:08 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Funcionalidad (2 puntos)**
❌ 0 puntos: No simula uno o más flujos de trabajo en términos de entrada, proceso y salida. No hay ningun flujo de trabajo completo, concentrarse en hacer una funcionalidad correcta, que represente entrada del usuario, procesamiento de un algoritmo, y nueamente una interacción de salida al usuario.
❌ 0 puntos: La funcionalidad no es apropiada al contexto del simulador. Puedo comprar una coca cola a 55000 en una página de venta de articulos deportivos.

- **Interactividad (2 puntos)**
✅ 1 punto: Captura entradas ingresadas por el usuario mediante eventos.
✅ 1 punto: Efectúa una o más salidas por HTML modificando el DOM, con control de ingreso de entradas y salidas coherentes en relación a los datos ingresados.

- **Escalabilidad (2 puntos)**
✅ 0.5 puntos: Declara funciones con parámetros para definir instrucciones con una tarea específica.
✅ 0.5 puntos: Emplea arrays para agrupar valores relacionados.
❌ 0 puntos: No define objetos con propiedades y métodos relevantes al contexto. Pensar en utilizar una clase Carrito y Producto.
❌ 0 puntos: No establece un criterio homogéneo para la detección de eventos y almacena en storage datos relevantes generados durante la simulación. No se usa nunca el [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)

- **Integridad (1 punto)**
✅ 0.5 puntos: Define el código JavaScript en un archivo .js, referenciándolo correctamente desde el HTML.
❌ 0 puntos: Evitá métodos prompt() y alert() para evitar interrupciones durante el procesamiento y actualización del DOM, y emplea adecuadamente la información estática del proyecto.

- **Legibilidad (1 punto)**
✅ 0.5 puntos: Los nombres de variables, funciones y objetos son significativos para el contexto.
⚠️ 0.25 puntos: Las instrucciones se escriben de forma legible y se emplean comentarios oportunos, manteniendo el código fuente ordenado en términos de declaración y secuencia. En algún punto el código hace demasiadas cosas, considero que con la clase `Carrito.js` se va solucionar.

- **GitHub (2 puntos):**
⚠️ 0.25 puntos: Realización de commits necesarios sobre la rama de desarrollo utilizando Git. Tenes conflictos de merge, no te va dejar hacer merge sin resolverlos.
❌ 0 puntos: Creación de una rama "feature/cuarta-entrega" a partir de la rama "develop" utilizando Git. Cuidado que la rama marca este aviso `This branch is [7 commits ahead of](https://github.com/armandopasilis/Programacion_web_uces/tree/feature/cuarta-entrega) master.` No queda nada más que verificar la proxima desde donde se parte el origen de la rama para crear otra.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/tercera-entrega" con "develop" en GitHub. 

**Nota: 8(ocho)**

2024-11-25 05:08 UTC, MVelasquez98 commented on script.js
> -import { Producto } from './Producto.js';
¿Por qué eliminas el uso de la clase Producto? Sigue siendo necesaria

2024-11-25 05:08 UTC, MVelasquez98 commented on script.js
> -import { Carrito } from './Carrito.js';
¿Por qué eliminas el uso de la clase Carrito? Sigue siendo necesaria

2024-11-25 05:08 UTC, MVelasquez98 commented on script.js
> +        alert("Ingrese un nombre y un precio válido para el producto.");
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Considera mostrar los mensajes de error en el formulario en lugar de usar ventanas emergentes. Podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [SweetAlert](https://sweetalert2.github.io/)

2024-11-25 05:08 UTC, MVelasquez98 commented on script.js
> +function addProductToCart(name, price) {
Usar una clase para el carrito: Implementa una clase para encapsular la lógica del carrito. Esto mejora la reutilización y la claridad. Por ejemplo:

```
class Carrito {
    constructor() {
        this.productos = JSON.parse(localStorage.getItem("carrito")) || [];
    }

    guardar() {
        localStorage.setItem("carrito", JSON.stringify(this.productos));
    }

    agregar(nombre, precio) {
        if (!esProductoValido(nombre, precio)) return;
        // Lógica de agregar...
    }

    // Otras funciones...
}

```

2024-11-25 05:08 UTC, MVelasquez98 commented on script.js
> +    if (name && price > 0) {
El código actual no valida si el campo de precio contiene un número válido. Esto puede generar errores si el usuario ingresa valores no numéricos. Además, no se verifica si productNameInput.value es un texto vacío o contiene solo espacios.
Agregar una validación más estricta usando [isNaN](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/isNaN) para el precio y comprobando que el nombre no sea una cadena vacía después de eliminar espacios en blanco.

2024-11-25 05:08 UTC, MVelasquez98 commented on script.js
> +addProductButton.addEventListener("click", () => {
La función addEventListener mezcla validación y lógica de negocio, lo que dificulta el mantenimiento y las pruebas unitarias. Crear funciones separadas para validar la entrada y agregar productos. 
```
addProductButton.addEventListener("click", handleAddProduct);

function handleAddProduct() {
    const name = productNameInput.value.trim();
    const price = Number(productPriceInput.value);
    
    if (validateInputs(name, price)) {
        addProductToCart(name, price);
        resetInputs();
    }
}
```

2024-11-25 05:08 UTC, MVelasquez98 commented on script.js
> +            cart.splice(index, 1); // Quita el producto del array
Si se eliminan elementos del carrito rápidamente, los índices pueden desincronizarse con el array original, causando errores. Usar una clave única (como un identificador de producto) en lugar del índice para eliminar productos. Agregar un identificador único a cada producto al momento de agregarlo al carrito.

2024-11-25 05:08 UTC, MVelasquez98 commented on script.js
> +        productText.textContent = `${product.name} - $${product.price}`;
Para mejorar la experiencia del usuario, se debe mostrar el precio con un formato consistente (dos decimales). Usar [toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed)(2) para garantizar el formato.

2024-11-25 20:02 UTC, armandopasilis commented on script.js
> +        productText.textContent = `${product.name} - $${product.price}`;
Realizado

2024-11-25 20:13 UTC, armandopasilis commented on script.js
> +            cart.splice(index, 1); // Quita el producto del array
Ahora cada producto tiene un id único generado con Date.now().
Los productos se eliminan usando su id en lugar del índice, evitando errores por cambios en el array.

2024-11-25 20:20 UTC, armandopasilis commented on script.js
> +    if (name && price > 0) {
uso isNaN(price) para verificar que el valor ingresado sea un número válido antes de compararlo con 0.Y para el nombre del producto me aseguro que no sea una cadena vacía ("") después de usar trim().

2024-11-25 20:25 UTC, armandopasilis commented on script.js
> +addProductButton.addEventListener("click", () => {
Realizado ,

2024-11-25 20:39 UTC, armandopasilis commented on script.js
> +        alert("Ingrese un nombre y un precio válido para el producto.");
Realizado

2024-11-25 20:47 UTC, armandopasilis commented on script.js
> -import { Producto } from './Producto.js';
Si lo habre eliminado en la convinacion  y la resolucion de errores

2024-11-25 20:47 UTC, armandopasilis commented on script.js
> -import { Carrito } from './Carrito.js';
Si lo habre eliminado en la convinacion  y la resolucion de errores

2024-11-25 21:04 UTC, armandopasilis commented on script.js
> +function addProductToCart(name, price) {
Realizado

2024-11-25 21:07 UTC, armandopasilis commented
Hola Profe aplique las correcciones , Solicito el LGTM para realizar el examen. Gracias Saludos

2024-11-26 02:26 UTC, MVelasquez98 commented
Este flujo no tiene ningun sentido, me permite agregar cualquier cosa al carrito ¿no deberia estar previamente configurado los productos que puedo elegir y el precio?:
<img width="1420" alt="image" src="https://github.com/user-attachments/assets/2d680fde-9156-4abb-971e-1582f5e3629c">

2024-11-26 02:26 UTC, MVelasquez98 commented
Revisar comentarios

2024-11-26 12:32 UTC, armandopasilis commented
> Este flujo no tiene ningun sentido, me permite agregar cualquier cosa al carrito ¿no deberia estar previamente configurado los productos que puedo elegir y el precio?: <img alt="image" width="1420" src="https://private-user-images.githubusercontent.com/43156596/389769250-2d680fde-9156-4abb-971e-1582f5e3629c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjE5MzEsIm5iZiI6MTczMjYyMTYzMSwicGF0aCI6Ii80MzE1NjU5Ni8zODk3NjkyNTAtMmQ2ODBmZGUtOTE1Ni00YWJiLTk3MWUtMTU4MmY1ZTM2MjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDExNDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YjMxNDE2Y2E4MWRkNGFjMDlmZmNmYjE5YTNiYzA2ZmEyNGRhYjA3NzQ2NTRjZDE0YTM1MmEyNTNiYTY1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jHv4wPEL1ggX5zlBCUvhYQIf4Ax-yQbvO4FsbTG4Izk">

ok aplique unos cambios para que sea limitado lo que se agrega al carrto : 
![image](https://github.com/user-attachments/assets/662e512c-e30f-45b4-b58f-219a15896412)

2024-11-26 23:40 UTC, MVelasquez98 approved these changes
LGTM

2024-11-26 23:40 UTC, MVelasquez98 commented on script.js
> -    const carrito = new Carrito();
Esto mismo, es lo que nunca haces ahora. No estas usando nunca la clase Carrito.js y sus métodos

2024-11-26 23:40 UTC, MVelasquez98 commented on script.js
> -                    } else {
A hacer uso de los métodos de carrito como hacias aca a esto me refiero, lo único que tiene que cambiar es que ya no hay un menu switch con prompt, ahora reemplazas eso por el uso de DOM y eventos, la logica del uso de clases es la misma

2024-11-26 23:40 UTC, MVelasquez98 commented on script.js
> +function removeProductFromCart(productId) {
Esto es un metodo dentro de la clase Carrito.js

2024-11-26 23:40 UTC, MVelasquez98 commented on script.js
> +function addProductToCart(name, price) {
Esto es un metodo dentro de la clase Carrito.js

2024-11-27 12:39 UTC, armandopasilis commented on script.js
> +function addProductToCart(name, price) {
Realizado
![image](https://github.com/user-attachments/assets/b2fa4569-2257-40f8-883f-d3da7fddd65a)

2024-11-27 12:40 UTC, armandopasilis commented on script.js
> +function removeProductFromCart(productId) {
![image](https://github.com/user-attachments/assets/446c65fd-ffed-4343-9359-c1b648d7c077)

2024-11-27 12:51 UTC, merged