Release/segundo parcial
armandopasilis/Programacion_web_uces pull request #16
Opened 2024-11-27 13:02 UTC by armandopasilis

Requerimientos para esta entrega:
1. Asincronía y Manejo de Datos
● Utilizarás AJAX y JSON para obtener datos de forma asíncrona,
implementando herramientas como promises y fetch para consumir
APIs. Se recomienda usar APIs como:
○ JSONPlaceholder
○ Mockaroo
○ Beeceptor
○ MockAPI
○ TheCocktailDB
○ FakeStoreAPI
○ TheMealDB
○ TheMovieDB
○ También puedes utilizar un archivo JSON estático incluido en el
proyecto, incluyendo dentro de una carpeta “api”.
● La información estática o obtenida de una API debe cargarse y
utilizarse de forma asíncrona.
● Implementa un recorrido óptimo de las colecciones utilizando funciones
de orden superior (map, filter, reduce, etc.).
● Captura entradas del usuario mediante inputs y eventos adecuados.
● Las salidas deben ser coherentes con las entradas y presentarse en el
HTML de forma asíncrona.
2. Gestión del Proyecto con GitHub
● Realizar commits significativos sobre la rama de desarrollo, siguiendo
buenas prácticas de Git para mantener un historial de cambios claro y
ordenado.
● Crear una rama release/segundo-parcial a partir de la rama develop
utilizando el flujo de trabajo de Git.
● Implementar un archivo CHANGELOG.md en el proyecto,
documentando los cambios realizados en cada entrega o versión con
un formato estructurado.
● Configurar reglas en el repositorio de GitHub para bloquear push
directos a las ramas develop y master. Se deben permitir únicamente
mediante pull requests.
● Requerir al menos un revisor aprobado para realizar merges en el
repositorio.
● Crear una plantilla (template) de pull requests para estandarizar las
solicitudes de revisión e incluir información relevante.

2024-11-27 21:23 UTC, MVelasquez98 commented
Antes de que entregues el parcial revisa que esta rema no esta deploy en GithubPages, y te falta toda la parte de **Gestión del Proyecto con GitHub**, revisa los requisitos de entrega, los archivos, template y configuraciones que te solicito.

2024-11-28 12:16 UTC, armandopasilis commented
![image](https://github.com/user-attachments/assets/2bc6a47a-93a1-466a-998f-4fdbb5fb99c3)
Reglas aplicadas a las ramas develop y master

2024-11-28 12:40 UTC, armandopasilis commented
![image](https://github.com/user-attachments/assets/0fedcbc0-c023-4523-a99d-c96a32cd329d)
Implemente una plantilla

2024-11-28 12:41 UTC, armandopasilis commented
git hub pages : 
https://armandopasilis.github.io/Programacion_web_uces/

2024-11-30 21:08 UTC, MVelasquez98 commented
No estan bien configuradas las reglas de bloqueo de merge sin un revisor:
- como se ve tu proyecto
![image](https://github.com/user-attachments/assets/98efdfb6-7157-4698-86ee-4200f5c55d31)
- como se deberia ver con la regla correctamente configurada:
![image](https://github.com/user-attachments/assets/32bdac8d-1dac-4f1f-bb94-cb4ae144e89a)

2024-11-30 21:16 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA**:
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Asincronía y Manejo de Datos (3 puntos)**
✅ 1 punto: Utiliza AJAX y JSON para obtener datos de forma asíncrona, manejando adecuadamente promises y fetch para consumir alguna API mock .
⚠️ 0.5 puntos: Todavía hay información estática que no esta en formato JSON, y no se carga y utiliza de manera asíncrona.
✅ 1 punto: Recorrido de colecciones siendo óptimo utilizando funciones de orden superior. 

- **Gestión del Proyecto y Buenas Prácticas con GitHub (7 puntos)**:
✅ 1 punto: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
✅ 1 punto: Creación de una rama release/segundo-parcial a partir de la rama develop utilizando Git.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama feature/cuarta-entrega con develop en GitHub.
✅ 1 punto: Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama release/segundo-parcial como parte de la entrega.
⚠️ 0.50 puntos: Implementa un archivo [CHANGELOG.md](https://github.com/Laboratoria/changelog-guide) documentando los cambios realizados en el proyecto en cada entrega o versión, siguiendo un formato estructurado. Revisar cambios propuestos, algo más completo. Tomar el comentario solo como modelo, rellenar correctamente.
❌ 0 puntos: No Configura [reglas en GitHub](https://docs.github.com/es/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) para bloquear push directos a las ramas develop y master, exigiendo pull requests con al menos un revisor aprobado para realizar merges. Incluir en el comentario de la pull request una captura con el estado de las reglas.
❌ 0 puntos: No Implementa una [plantilla (template) de pull request](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) en el repositorio para estandarizar las solicitudes de revisión y asegurarse de incluir in[formación relevante](https://axolo.co/blog/p/part-3-github-pull-request-template) (descripción, cambios realizados, pruebas realizadas, etc.). 

**Nota**: 7(Siete)

**Comentarios**: Hiciste un buen progreso hasta ahora, y se nota el esfuerzo puesto en el proyecto. Sin embargo, hay áreas clave que requieren atención y mejora antes de la entrega final. Aca te dejo algunas recomendaciones finales:

1. **Asincronía y Manejo de Datos:** 
   - Aún queda pendiente trabajar sobre la carga asíncrona de toda la información estática desde archivos JSON. Esto no solo optimiza el rendimiento de la aplicación, sino que también cumple con las mejores prácticas de desarrollo moderno. Intenta convertir más componentes de tu aplicación para funcionar con JSON cargado dinámicamente y asíncronamente.

2. **Gestión del Proyecto y Buenas Prácticas con GitHub:**
   - **CHANGELOG:** Asegúrate de que tu `CHANGELOG.md` esté bien estructurado y detallado, reflejando todos los cambios en cada versión. Esto te beneficia al mantener un historial claro de las mejoras y correcciones realizadas.
   - **Reglas de Protección y Flujos en GitHub:** Es crucial configurar las reglas para proteger las ramas principales (`develop` y `master`) y requerir revisiones para las pull requests. Esto asegura que el código se desarrolle de manera colaborativa y segura. 
   - **Plantillas de Pull Request:** Implementa una plantilla de pull request para estandarizar la documentación y revisión de cambios. Esto facilitará la colaboración en equipo y asegurará que la información crítica esté siempre documentada.

3. **Enfocarse en los Detalles Finales:**
   - Realiza pruebas exhaustivas de tu aplicación para identificar y corregir cualquier problema restante, **0 errores en consola**
  
Si te concentras en estos aspectos no solo mejorará la calidad de tu proyecto, sino que también te ofrecerá la confianza necesaria para presentar y defender tu trabajo de manera efectiva durante el examen final. ¡Continúa con el gran esfuerzo y exitos!

2024-11-30 21:16 UTC, MVelasquez98 commented on CHANGELOG.MD
En la materia no fuimos manejando un número de versiones especifico, ordena las fechas y los cambios por las entregas reales que hiciste:
- Actividad obligatoria N°1
- Actividad obligatoria N°2
- Actividad obligatoria N°3 
- Actividad obligatoria N°4
- Primer Parcial
- Segundo Parcial

2024-11-30 21:16 UTC, MVelasquez98 commented on index.html
> +
No incluyas HTML comentado, si ya no se utiliza, se elimina, se borra

2024-11-30 21:16 UTC, MVelasquez98 commented on index.html
> +                        <ul id="productList"></ul>
Si ya no se utiliza se borra, no se comenta

2024-11-30 21:16 UTC, MVelasquez98 commented on script.js
> +// Mostrar productos en el HTML
Si este código ya no se utiliza, se elimina, se borra, no se comenta

2024-11-30 21:16 UTC, MVelasquez98 commented on script.js
> +function actualizarVistaCarrito() {
¿Este no es un método dentro de la clase carrito?
`carrito.actualizarVista()`

2024-11-30 21:16 UTC, MVelasquez98 commented on script.js
> +        errorMessage.textContent = message;
Error en consola ¿donde esta definido `errorMessage`?
![image](https://github.com/user-attachments/assets/7096aec8-407a-45bb-8377-0009812b3482)

2024-11-30 21:16 UTC, MVelasquez98 commented on script.js
> +const productosDisponibles = [
Estos productos estaticos se tienen que reemplazar por el uso de un archivo JSON aparte, es decir deberias usar el JSON que ya tenes `productos.json`

2024-11-30 21:16 UTC, MVelasquez98 commented on script.js
> +    productosDisponibles.map(producto => {
Reemplaza `map` por `forEach` para crear elementos del DOM, ya que map está diseñado para transformar arrays y esperar un uso del resultado, lo cual no es necesario aca. Además, asegúrate de limpiar el contenido previo antes de insertar nuevas opciones.

2024-12-04 15:29 UTC, armandopasilis commented
> No estan bien configuradas las reglas de bloqueo de merge sin un revisor:
> 
> * como se ve tu proyecto
>   ![image](https://private-user-images.githubusercontent.com/43156596/391287888-98efdfb6-7157-4698-86ee-4200f5c55d31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjYyMTQsIm5iZiI6MTczMzMyNTkxNCwicGF0aCI6Ii80MzE1NjU5Ni8zOTEyODc4ODgtOThlZmRmYjYtNzE1Ny00Njk4LTg2ZWUtNDIwMGY1YzU1ZDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1MjUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYzJhM2E4MzEwNGI0ZGFhN2JlMTQxN2QzNmQyNmM2YzJlZDY3ZDY5YjQ4NDNlYWQ2OTdkOWE3MDIyMjAzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MlxZiQVBgnAgX51vgvt6cK_r2KXGT7fniMwx5hlfkck)
> * como se deberia ver con la regla correctamente configurada:
>   ![image](https://private-user-images.githubusercontent.com/43156596/391288049-32bdac8d-1dac-4f1f-bb94-cb4ae144e89a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjYyMTQsIm5iZiI6MTczMzMyNTkxNCwicGF0aCI6Ii80MzE1NjU5Ni8zOTEyODgwNDktMzJiZGFjOGQtMWRhYy00ZjFmLWJiOTQtY2I0YWUxNDRlODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE1MjUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZGY4YWQxOGY0YTBhNmRjMzQyYThlOTc3NzdiZDkzYzQwZjA5OTM0Y2M4NThlNTc3YTBlMzc2ZDljMTBkMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MpUqerJ2bCWEQliVNneWxNfJOPUzRupOkMjtMRM4rmc)

Creo que la cree pero no la aplico . Ahora se ve bien ?

2024-12-04 15:54 UTC, MVelasquez98 commented
Ahora si se ve bien:
![image](https://github.com/user-attachments/assets/518a5548-6689-49a8-8c41-f75c505a1422)

2024-12-06 12:04 UTC, armandopasilis commented on script.js
> +const errorMessage = document.getElementById("errorMessage");
Aca defini errorMessage

2024-12-06 13:01 UTC, armandopasilis commented on script.js
> +const productosDisponibles = [
realizado

2024-12-06 13:03 UTC, armandopasilis commented on script.js
> +    productosDisponibles.map(producto => {
Realizado

2024-12-12 16:17 UTC, MVelasquez98 approved these changes
LGTM

2025-12-16 11:35 UTC, armandopasilis commented
Se cierra pedido del profesor

2025-12-16 14:26 UTC, merged