Feature/segunda entrega
armandopasilis/Programacion_web_uces pull request #6
Opened 2024-09-10 13:19 UTC by armandopasilis

-Nueva sección "box" en HTML
-Se añadió una nueva sección con varios div dentro de una clase box para mostrar productos destacados.
-Se utilizó el modelo Flexbox para organizar el contenido dentro de la clase box de manera flexible.
-Se agrego e Flexbox
-display: flex: Permite alinear los elementos de manera horizontal.
-flex-wrap: wrap: Los elementos pueden ajustarse en múltiples filas si no hay suficiente espacio.
-gap: 20px: Se añadió un espacio entre los elementos.
-justify-content: space-between: Los elementos dentro de la clase box se espacian uniformemente.
-Flexibilidad en los elementos:
-Se agregó flex: 1 1 200px a los div de la clase box-item, lo que asegura que cada elemento tenga un ancho mínimo de 200px y que se ajuste dinámicamente.
-se agregaron estilos visuales:
-Se implementó un media query (@media (max-width: 768px)) para que los elementos dentro de la clase box cambien de un diseño en fila a uno en columna en pantallas pequeñas, como móviles o tablets.

2024-09-10 21:42 UTC, armandopasilis commented on index.html
> -    <title>Document</title>
Esto se cambio

2024-09-10 21:43 UTC, armandopasilis commented on index.html
> +         <!-- Nueva sección con clase "box" -->
aca puse una clase nueva  "contenedor "

2024-09-25 16:05 UTC, MVelasquez98 requested changes
Revisa las media querys para dispositivos moviles, no esta siendo responsivo en todas las secciones, algo en flex no esta funcionando:

<img width="643" alt="image" src="https://github.com/user-attachments/assets/3e090c93-9f5a-4cd5-be59-0737f3f62932">

2024-09-25 16:07 UTC, MVelasquez98 commented
@armandopasilis Recorda respetar el flujo de trabajo GitFlow, solo haces rebase and merge cuando yo te de LGTM a tu pull request, y los cambios solicitados se hacen sobre la misma rama como lo especifica la consigna de la actividad.
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/221173fa-8772-4fe0-ae5f-6c191079e790">

2024-09-25 16:14 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Mejoras en la Maquetación CSS (5 puntos):**
- Implementación eficaz de diferentes tipos de selectores y aprovechamiento de la herencia de estilos para simplificar el código CSS. (1 punto) ✅ 
- Aplicación correcta de formatos y fuentes para mejorar la legibilidad y estética del contenido, utilizando las propiedades CSS correspondientes. (1 punto) ✅ 
- Uso adecuado de modelos de caja (box model) para controlar el tamaño, margen, relleno y bordes de los elementos de la página. (1 punto) ✅ 
- Diferenciación clara entre elementos en línea y elementos en bloque mediante estilos CSS apropiados, demostrando comprensión de las diferencias y su aplicación en el diseño web. (1 punto) ✅ 
- Implementación efectiva de columnas utilizando técnicas como elementos flotantes, display: flex y display: grid, según corresponda al diseño requerido. (1 punto) ✅ 

**Diseño de Columnas y Layouts Responsive (2 puntos):**
- Correcta utilización de media queries para crear un diseño responsive que se adapte de manera adecuada a diferentes tamaños de pantalla y dispositivos. (1 punto) ⚠️ Revisar algunas secciones que no se ven del todo responsive en dispositivos moviles
- Estructuración satisfactoria de layouts utilizando contenedores, filas y columnas, demostrando comprensión de los conceptos de diseño responsivo y su aplicación práctica. (1 punto) ⚠️ Hace uso de Flexbox en todo el documento, eso va mejorar la UX, sobre todo en dispositivos moviles. Podes ver como se vería tu página en un celular desde el inspector de chrome o el navegador que utilices

**GitHub (3 puntos):**
- Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto) ✅ 
- Creación de una rama "feature/segunda-entrega" a partir de la rama "develop" utilizando Git. (1 punto) ⚠️ Tenes conflictos de git merge al intentar hacer rebase and merge, recorda que siempre tenes que hacer pull de develop antes de crear otra PR contra develop.
- Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/primera-entrega" con "develop" en GitHub. (1 punto) ❌  No esperaste mi LGTM✅ para hacer rebase and merge de la primera entrega, pierdo trazabilidad de si realizaste bien los cambios o no.

**Nota:** 7 (Siete)

2024-09-25 16:53 UTC, armandopasilis commented
![Captura](https://github.com/user-attachments/assets/31c4f718-91b1-4dc3-8338-c303e2e5a365)
Hola Profe , como esta? . Muchas gracias por el feed back . Voy a ver la configuracion de la imagen que paso . Disculpe lo del LGTM , entendi que si me la habia aprobado , me habia llegado un mail ( se lo paso ) y en Git tambien me figuraba , pero como es nuevo no entiendo muy bien .

2024-10-01 13:04 UTC, armandopasilis commented
![image](https://github.com/user-attachments/assets/b78dd1ad-5801-42d3-bc4b-f1117f4145c3)
solucionado

2024-10-01 13:14 UTC, armandopasilis commented
@MVelasquez98  Hola profe , me tiene que dar el LGTM para el parcial aqui no ?

2024-10-01 18:43 UTC, MVelasquez98 commented
Correcto, revisa este punto: 

> ⚠️ Tenes conflictos de git merge al intentar hacer rebase and merge, recorda que siempre tenes que hacer pull de develop antes de crear otra PR contra develop.

Aunque te de approve no te va dejar hacer merge, por los [conflictos](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) que hay:
<img width="871" alt="image" src="https://github.com/user-attachments/assets/023db918-354c-4596-8804-380d82fdc644">
Podes hacer lo siguiente en tu local:

- Te moves a `develop`
- Haces `git pull`
- Volves a la rama `feature/segunda-entrega`
- Haces desde vscode ... -> Rama -> Fusionar la rama mediante "rebase"
<img width="974" alt="image" src="https://github.com/user-attachments/assets/9afdd178-7a19-4f3d-a24c-80f423bd4a11">
- [Resolves los conflictos ](https://www.jorgeacortes.com/2019/01/resolver-conflictos-en-git-con-visual-studio-code/)que esten en los archivos marcados con advertencia ⚠️
- Asegurate de no pisar tus cambios
- Hace `git add .`
- Le das "Continuar" (el boton azul)
- Haces `git push -f`

Algunos videos que te pueden servir:
[Como Solucionar un Merge Conflict (Conflicto de Merge) En VSCode](https://youtu.be/uDDNwwxoaZY?si=eGG_ZhIXRfYpEmnn)
[Cómo resolver conflictos de versiones con VS Code
](https://youtu.be/g7bbxEt09PI?si=bi26br5lpoyPY3-w)

2024-10-01 19:33 UTC, armandopasilis commented
reopen

2024-10-01 19:33 UTC, armandopasilis commented
Reopend

2024-10-01 19:34 UTC, armandopasilis commented
a

2024-10-01 19:34 UTC, armandopasilis commented
Opend

2024-10-01 19:42 UTC, armandopasilis commented
@MVelasquez98 Ahi esta profe , algun comando me borro todo , habia echo una copia antes . ahora figura en verde

2024-10-01 19:58 UTC, armandopasilis commented
![image](https://github.com/user-attachments/assets/d9acdc2d-8c29-42e7-9169-25d7664b0730)

2024-10-01 19:58 UTC, MVelasquez98 approved these changes
LGTM
Fijate que sigue marcando conclicto al hacer `rebase and merge`, no te va dejar hacer   merge. ¿Resolviste los [conflictos](https://stackoverflow.com/questions/50012036/github-cant-rebase-my-feature-branch-this-branch-cannot-be-rebased-due-to-con)?
<img width="925" alt="image" src="https://github.com/user-attachments/assets/8829307f-aea8-49a2-8a7a-679f1abd2259">

2024-10-01 19:59 UTC, merged

2024-10-01 20:01 UTC, MVelasquez98 commented
Es "Rebase and mege" contra `develop`, no "Merge Pull request", solo usamos "merge pull request" cuando hacemos pull request contra master. Es posible que al hacer merge se hallan pisado tus cambios. 
Lo dice la consigna:
<img width="589" alt="image" src="https://github.com/user-attachments/assets/ecf2dedb-7873-4994-8a10-8f91240be0d4">

2024-10-01 20:12 UTC, armandopasilis commented
que me recomienda generar otra pull request de segunda entrega ?
no me figuraba ninguna falla de archivos
solo este error fatal: no rebase in progress
________________________________
De: Matias Velasquez ***@***.***>
Enviado: martes, 1 de octubre de 2024 17:02
Para: armandopasilis/Programacion_web_uces ***@***.***>
Cc: armandopasilis ***@***.***>; State change ***@***.***>
Asunto: Re: [armandopasilis/Programacion_web_uces] Feature/segunda entrega (PR #6)


Es "Rebase and mege" contra develop, no "Merge Pull request", solo usamos "merge pull request" cuando hacemos pull request contra master. Es posible que al hacer merge se hallan pisado tus cambios.
Lo dice la consigna:
image.png (view on web)<https://github.com/user-attachments/assets/ecf2dedb-7873-4994-8a10-8f91240be0d4>

—
Reply to this email directly, view it on GitHub<https://github.com/armandopasilis/Programacion_web_uces/pull/6#issuecomment-2386949518>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIJK45CQLWMGY5CYBL53ZG3ZZL5T3AVCNFSM6AAAAABN6YBCIGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOBWHE2DSNJRHA>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>